name: Check for Available Rooms

on:
  schedule:
    - cron: "*/10 * * * *" # Run every 10 minutes
  workflow_dispatch: # Also allow manual triggering

jobs:
  check-rooms:
    runs-on: ubuntu-latest
    steps:
      - name: Call Room Check API
        run: |
          curl -s -X GET "${{ secrets.UR_CHECK_APP_URL }}/api/room_check" || echo "API request failed"
