name: Check for Available Rooms

on:
  schedule:
    - cron: "*/10 0-10 * * *" # JST 9:00-19:50 (UTC 0:00-10:50)
  workflow_dispatch: # allow manual triggering

jobs:
  check-rooms:
    runs-on: ubuntu-latest
    steps:
      - name: Record start time
        env:
          TZ: "Asia/Tokyo"
        run: echo "Job started at $(date)"

      - name: Call Room Check API
        run: |
          curl -s -X GET "${{ secrets.UR_CHECK_APP_URL }}/api/room_check" -H "Authorization: Bearer ${{ secrets.CHECK_ROOMS_SECRET }}" || echo "API request failed"

      - name: Record end time
        env:
          TZ: "Asia/Tokyo"
        run: echo "Job completed at $(date)"
